<?php

namespace SchedulingBundle\Repository;

/**
 * DistributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributionRepository extends \Doctrine\ORM\EntityRepository
{
}
