<?php

namespace SchedulingBundle\Repository;

/**
 * ScheduleBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
