<?php

namespace SchedulingBundle\Repository;

/**
 * BreakRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleBreakRepository extends \Doctrine\ORM\EntityRepository
{
}
