<?php

namespace SchedulingBundle\Repository;

/**
 * TimeOffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeOffRepository extends \Doctrine\ORM\EntityRepository
{
}
