services:
#    auth.example:
#        class: AuthBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


# user edit form
    UserEditType:
        class: AuthBundle\Form\UserEditType
        tags:
            - { name: form.type}