app:
    resource: "@AppBundle/Controller/"
    type:     annotation

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
    #prefix: /auth
    
staffing:
    resource: "@StaffingBundle/Resources/config/routing.yml"

ticket:
    resource: "@TicketBundle/Resources/config/routing.yml"

scheduling:
    resource: "@SchedulingBundle/Controller/"
    type:     annotation    

