app:
    resource: "@AppBundle/Controller/"
    type:     annotation

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
    #prefix: /auth

callcenter:
    resource: "@CallcenterBundle/Resources/config/routing.yml"

ticket:
    resource: "@TicketBundle/Resources/config/routing.yml"