app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
       

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
    #prefix: /auth
