# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        #default user class
        #Symfony\Component\Security\Core\User\User:
        #    algorithm: bcrypt
        #    cost: 12
        AuthBundle\Entity\User: bcrypt
            
        
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_EVENT_CREATE]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
           memory: ~
        #        users:
        #            admin:
        #                password: $2y$12$1eodzD7Bmpg7G3zpN/SCbuiuy1p7bjDM5aRtfI0aW6BfKdv3FqcHi
        #                roles: 'ROLE_ADMIN'
        
        database:
            entity:
                class: AuthBundle:User

                    
                        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            switch_user: true
            anonymous: ~
            pattern:    ^/            
            provider: database
            form_login:
                login_path: login
                check_path: login     
                success_handler: auth.authentication_event_listener
            logout: 
                path: logout
                target: /                                
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
