<?php

namespace CallcenterBundle\Repository;

/**
 * CostCenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostCenterRepository extends \Doctrine\ORM\EntityRepository
{
}
