<?php

namespace CallcenterBundle\Repository;

/**
 * ServiceUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
