<?php

namespace CallcenterBundle\Repository;

/**
 * StakeHolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StakeHolderRepository extends \Doctrine\ORM\EntityRepository
{
}
