<?php

namespace CallcenterBundle\Repository;

/**
 * WorkForceAllocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkForceAllocationRepository extends \Doctrine\ORM\EntityRepository
{
}
