<?php

namespace TicketBundle\Repository;

/**
 * TicketQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketQueueRepository extends \Doctrine\ORM\EntityRepository
{
}
