<?php

namespace TicketBundle\Repository;

/**
 * TicketPriorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketPriorityRepository extends \Doctrine\ORM\EntityRepository
{
}
