<?php

namespace TicketBundle\Repository;

/**
 * TicketCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
