<?php

namespace TicketBundle\Repository;

/**
 * TicketAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
